### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 0)

### ISSUE THREAD

**Issue by rengar011** [taishan1994/OneRel_chinese#23]
data_loader.py文件中
 token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)
ValueError: not enough values to unpack (expected 7, got 0)
batch是个空列表😵

**Comment by taishan1994** [comment]
打印下加载数据是否正确

**Comment by zjutnlper** [comment]
我也遇到这样的问题，你解决了吗

**Comment by XuperX** [comment]
我也遇到了这个问题，我把max_len 设成了1000 但并没有解决问题 
```
Traceback (most recent call last):
  File "/net/scratch2/h72537fx/20240201/OneRel/train.py", line 60, in <module>
    fw.train(model[args.model_name])
  File "/net/scratch2/h72537fx/20240201/OneRel/framework/framework.py", line 96, in train
    data = train_data_prefetcher.next()
  File "/net/scratch2/h72537fx/20240201/OneRel/data_loader.py", line 161, in next
    self.preload()
  File "/net/scratch2/h72537fx/20240201/OneRel/data_loader.py", line 149, in preload
    self.next_data = next(self.loader)
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/iusers01/fatpou01/compsci01/h72537fx/.conda/envs/OneRel_venv_0205/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/net/scratch2/h72537fx/20240201/OneRel/data_loader.py", line 101, in re_collate_fn
    token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)
ValueError: not enough values to unpack (expected 7, got 0)
```

**Comment by XuperX** [comment]
你好，我也遇到了相同的问题。
我尝试了以下解决方法但是还是没有头绪
  1）改变max_len=750 （虽然按照data——loader 不需要改变max——len
  2）print out L105 可以打印正常的tensor
但是我的数据可以跑几个epoch 之后才出现expected 7， got 0的error。我怀疑是某段text有问题。所以我单独取出tokenizer，把所有的text，triples 给tokenize 了。没有报错。
但按照data——loader 里的内容，我理解只要能成功tokenize就一定能生成7 个变量。
我不清楚哪里出了问题，希望能得到您的建议。

**Comment by 32209056** [comment]
你好，我也是跑完五个循环后，eval mode……，就会报上面的错，要改max_len改成多少啊

**Comment by XuperX** [comment]
@32209056 max_len 应该要调到比数据里最长的text大一点。
但是按照data loader里这行
```
    def __getitem__(self, idx):
        ins_json_data = self.json_data[idx]
        text = ins_json_data['text']
        text = ' '.join(text.split()[:self.config.max_len])
        tokens = self.tokenizer.tokenize(text)

        if len(tokens) > self.config.bert_max_len:
            tokens = tokens[: self.config.bert_max_len]
        text_len = len(tokens)
```
但我觉得，如果max——len 小于最长字符的话，应该只是丢失了部分数据，而不是跑不出来？

**Comment by zjutnlper** [comment]
> @32209056 max_len 应该要调到比数据里最长的text大一点。 但是按照data loader里这行
> 
> ```
>     def __getitem__(self, idx):
>         ins_json_data = self.json_data[idx]
>         text = ins_json_data['text']
>         text = ' '.join(text.split()[:self.config.max_len])
>         tokens = self.tokenizer.tokenize(text)
> 
>         if len(tokens) > self.config.bert_max_len:
>             tokens = tokens[: self.config.bert_max_len]
>         text_len = len(tokens)
> ```
> 
> 但我觉得，如果max——len 小于最长字符的话，应该只是丢失了部分数据，而不是跑不出来？

你好，这个问题我觉得是你的数据问题，我一开始也有这个问题，是因为我的数据里gold标签里的实体不在text中所以报错了，我把有问题的数据改了后就好了

**Comment by zjutnlper** [comment]
> 你好，这个问题我觉得是你的数据问题，我一开始也有这个问题，是因为我的数据里gold标签里的实体不在text中所以报错了，我把有问题的数据改了后就好了

**Comment by zjutnlper** [comment]
> 你好，我也遇到了相同的问题。 我尝试了以下解决方法但是还是没有头绪 1）改变max_len=750 （虽然按照data——loader 不需要改变max——len 2）print out L105 可以打印正常的tensor 但是我的数据可以跑几个epoch 之后才出现expected 7， got 0的error。我怀疑是某段text有问题。所以我单独取出tokenizer，把所有的text，triples 给tokenize 了。没有报错。 但按照data——loader 里的内容，我理解只要能成功tokenize就一定能生成7 个变量。 我不清楚哪里出了问题，希望能得到您的建议。

你好，这个问题我觉得是你的数据问题，我一开始也有这个问题，是因为我的数据里gold标签里的实体不在text中所以报错了，我把有问题的数据改了后就好了

**Comment by 32209056** [comment]
> > @32209056 max_len 应该要调到比数据里最长的text大一点。 但是按照data loader里这行
> > ```
> >     def __getitem__(self, idx):
> >         ins_json_data = self.json_data[idx]
> >         text = ins_json_data['text']
> >         text = ' '.join(text.split()[:self.config.max_len])
> >         tokens = self.tokenizer.tokenize(text)
> > 
> >         if len(tokens) > self.config.bert_max_len:
> >             tokens = tokens[: self.config.bert_max_len]
> >         text_len = len(tokens)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但我觉得，如果max——len 小于最长字符的话，应该只是丢失了部分数据，而不是跑不出来？
> 
> 你好，这个问题我觉得是你的数据问题，我一开始也有这个问题，是因为我的数据里gold标签里的实体不在text中所以报错了，我把有问题的数据改了后就好了

谢谢，确实形成的dev_json有问题,重新下载一下代码，作者有更新，能跑出来
