### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 0)

### ISSUE THREAD

**Issue by wangxiaoming-1997-code** [taishan1994/OneRel_chinese#3]
您好，麻烦请问一下，刚开始运行您的数据集的时候会报这样的错，后来莫名其妙能运行了，现在我换了一个数据集之后运行就又会报错，运行不下去，这是什么原因吗？
Traceback (most recent call last):
  File "D:/pythonproject/OneRel_chinese-main/train.py", line 48, in <module>
    fw.train(model[args.model_name])
  File "D:\pythonproject\OneRel_chinese-main\framework\framework.py", line 99, in train
    data = train_data_prefetcher.next()
  File "D:\pythonproject\OneRel_chinese-main\data_loader.py", line 174, in next
    self.preload()
  File "D:\pythonproject\OneRel_chinese-main\data_loader.py", line 162, in preload
    self.next_data = next(self.loader)
  File "D:\code\Anaconda3\envs\OneRel_chinese-main\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\code\Anaconda3\envs\OneRel_chinese-main\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\code\Anaconda3\envs\OneRel_chinese-main\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\pythonproject\OneRel_chinese-main\data_loader.py", line 111, in re_collate_fn
    token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)
ValueError: not enough values to unpack (expected 7, got 0)

Process finished with exit code 1

**Comment by taishan1994** [comment]
> batch

你的batch可能是空的，检查一下数据。

**Comment by Yun-Peng-Wang** [comment]
我也遇到了这个问题

**Comment by taishan1994** [comment]
> 我也遇到了这个问题

data_loader.py 105行打印一下batch，看看是什么。

**Comment by Yun-Peng-Wang** [comment]
> 
是空列表，我试NYT是可以的，然后我自己换了一个中文的数据集，用的中文预训练模型，格式也转成一样的了，没找到是什么原因

**Comment by Yun-Peng-Wang** [comment]
> > 我也遇到了这个问题
> 
> data_loader.py 105行打印一下batch，看看是什么。

是空列表，我试NYT是可以的，然后我自己换了一个中文的数据集，用的中文预训练模型，格式也转成一样的了，没找到是什么原因

**Comment by Yun-Peng-Wang** [comment]
> > > 我也遇到了这个问题
> > 
> > 
> > data_loader.py 105行打印一下batch，看看是什么。
> 
> 是空列表，我试NYT是可以的，然后我自己换了一个中文的数据集，用的中文预训练模型，格式也转成一样的了，没找到是什么原因

解决了，是数据有问题

**Comment by Yun-Peng-Wang** [comment]
> > > 我也遇到了这个问题
> > 
> > 
> > data_loader.py 105行打印一下batch，看看是什么。
> 
> 是空列表，我试NYT是可以的，然后我自己换了一个中文的数据集，用的中文预训练模型，格式也转成一样的了，没找到是什么原因

解决了，感谢，是tokenizer的问题，我用了onerel原版的tokenizer
